name: Build and Deploy Java Maven Project

on:
  push:
    branches:
      - main

env:
  TOMCAT_USER: username
  TOMCAT_PASSWORD: password

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@master
      with:
        host: CD-IN-LAP-R-136
        username: username
        password: password
        script: |
          echo "Stopping Tomcat server"
          sudo systemctl stop tomcat

          echo "Removing existing webapp directory"
          sudo rm -rf /var/lib/tomcat8/webapps/Test.war

          echo "Copying new war file to Tomcat webapps directory"
          sudo cp target/Test.war /var/lib/tomcat8/webapps/

          echo "Starting Tomcat server"
          sudo systemctl start tomcat
